// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SerratusTest.ORM;

namespace SerratusTest.Migrations
{
    [DbContext(typeof(SerratusSummaryContext))]
    [Migration("20201012201521_Summary2")]
    partial class Summary2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SerratusTest.Domain.Model.Family", b =>
                {
                    b.Property<int>("family_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("coverage_bins")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("depth")
                        .HasColumnType("double precision");

                    b.Property<int>("family_line")
                        .HasColumnType("integer");

                    b.Property<string>("family_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("length")
                        .HasColumnType("integer");

                    b.Property<int>("n_global_reads")
                        .HasColumnType("integer");

                    b.Property<int>("n_reads")
                        .HasColumnType("integer");

                    b.Property<int>("percent_identity")
                        .HasColumnType("integer");

                    b.Property<int?>("run_id")
                        .HasColumnType("integer");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<string>("sra_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("top_genbank_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("top_length")
                        .HasColumnType("integer");

                    b.Property<string>("top_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("top_score")
                        .HasColumnType("integer");

                    b.HasKey("family_id");

                    b.HasIndex("run_id");

                    b.ToTable("family");
                });

            modelBuilder.Entity("SerratusTest.Domain.Model.Run", b =>
                {
                    b.Property<int>("run_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("genome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("read_length")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sra_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("run_id");

                    b.ToTable("run");
                });

            modelBuilder.Entity("SerratusTest.Domain.Model.Sequence", b =>
                {
                    b.Property<int>("sequence_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("coverage_bins")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("depth")
                        .HasColumnType("double precision");

                    b.Property<int?>("family_id")
                        .HasColumnType("integer");

                    b.Property<string>("family_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("genbank_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("genbank_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("length")
                        .HasColumnType("integer");

                    b.Property<int>("n_global_reads")
                        .HasColumnType("integer");

                    b.Property<int>("n_reads")
                        .HasColumnType("integer");

                    b.Property<int>("percentage_identity")
                        .HasColumnType("integer");

                    b.Property<int?>("run_id")
                        .HasColumnType("integer");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<int>("sequence_line")
                        .HasColumnType("integer");

                    b.Property<string>("sra_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("sequence_id");

                    b.HasIndex("family_id");

                    b.HasIndex("run_id");

                    b.ToTable("sequence");
                });

            modelBuilder.Entity("SerratusTest.Domain.Model.Family", b =>
                {
                    b.HasOne("SerratusTest.Domain.Model.Run", null)
                        .WithMany("family")
                        .HasForeignKey("run_id");
                });

            modelBuilder.Entity("SerratusTest.Domain.Model.Sequence", b =>
                {
                    b.HasOne("SerratusTest.Domain.Model.Family", null)
                        .WithMany("sequence")
                        .HasForeignKey("family_id");

                    b.HasOne("SerratusTest.Domain.Model.Run", null)
                        .WithMany("sequence")
                        .HasForeignKey("run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
